from fastapi import APIRouter, Header

router = APIRouter()

@router.post("/")
def chat(query: str, authorization: str = Header(...)):
    return {
        "answer": "This will be generated by RAG engine"
    }
